-- CREATING DATAMART DATABASE AND TABLES

-- Create the WWBI datamart
CREATE DATABASE [WWBI_DWH] 
CONTAINMENT = NONE 
ON PRIMARY 
( NAME = N'WWBI_DWH', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\WWBI_DWH.mdf', SIZE = 73728KB, MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB)
LOG ON 
(NAME = N'WWBI_DWH_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\WWBI_DWH_log.ldf', SIZE = 73728KB, MAXSIZE = 2048GB, FILEGROWTH = 65536KB)
WITH CATALOG_COLLATION = DATABASE_DEFAULT 
GO

-- Create table [DIM_COUNTRY] 
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON 
GO

CREATE TABLE [dbo].[DIM_COUNTRY] (
[ID_COUNTRY] [varchar](3) NOT NULL, 
[DESC_COUNTRY] [varchar](250) NULL, 
[IS02] [varchar](250) NULL, 
[DESC_CURRENCY] [varchar](250) NULL, 
[DESC_REGION] [varchar](250) NULL,
[DESC_INCOME_GROUP] [varchar](250) NULL, 
) ON [PRIMARY]
GO

-- Create table [DIM_METRICAS] 
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DIM_METRICAS] (
[ID_INDICATOR] [varchar](250) NOT NULL,
[DESC_INDICATOR] [varchar](2500) NULL, 
) ON [PRIMARY]
GO

-- Create table [FACT_WWBI] 
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FACT_WWBI](
[ID_COUNTRY] [varchar](3) NULL, 
[ID_INDICATOR] [varchar](250) NULL, 
[ID_YEAR] INT NULL,
[IN_VALUE] FLOAT NULL
) ON [PRIMARY] 
GO