-- How many countries belong to each income group?
SELECT DISTINCT 
COUNT(DESC_COUNTRY) AS COUNTRIES_PER_INCOME_GROUP, DESC_INCOME_GROUP 
FROM WWBI_DWH.dbo.DIM_COUNTRY 
GROUP BY DESC_INCOME_GROUP

-- How many metrics are there, that have non-zero value in the year 2000?
SELECT COUNT(ID_INDICATOR) AS METRICS_WITHOUT_NULLS 
FROM WWBI_DWH.dbo.FACT_WWBI 
WHERE ID_YEAR = 2000 AND ID_YEAR > 1